# Generated by Django 5.0.3 on 2024-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='bibliografia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='cargahorariasemanal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='cargahorariasemestral',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='condicion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='curso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='evaluacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='fundamentacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='metodologia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='requisitos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='semestre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='objetivos',
            field=models.TextField(default=''),
        ),
    ]
