# Generated by Django 5.0.3 on 2024-04-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdf_bibliografia_pdf_cargahorariasemanal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='fundamentacion',
            new_name='fundamentación',
        ),
    ]
