# Generated by Django 5.0.3 on 2024-04-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fundamentacion_pdf_fundamentación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='fundamentación',
            new_name='fundamentacion',
        ),
    ]
