# Generated by Django 5.0.3 on 2024-04-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pdf_bibliografia_alter_pdf_cargahorariasemanal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='metodologia',
        ),
    ]
