# Generated by Django 5.0.3 on 2024-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pdf_contenido_remove_pdf_metodologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='contenido',
            field=models.TextField(default='Valor predeterminado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='metodologia',
            field=models.TextField(default='Valor predeterminado'),
            preserve_default=False,
        ),
    ]
