# Generated by Django 5.0.3 on 2024-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pdf_cargahorariasemanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='bibliografia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='carga_horaria_semanal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='carga_horaria_semestral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='condicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='evaluacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='fundamentacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='metodologia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='requisitos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='semestre',
            field=models.CharField(max_length=50),
        ),
    ]
